# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc1c4dec43fcae29f3db49302f8351d50c327ad450fc8b1c3f55d572c5406c00d31a4e1188f11f8df2a0a930fcc3405c5f612c7bc51fcfc98059fedded4abacd

test:
  secret_key_base: f9c5c370a25d91dc9cfdeea15913993875700c9e83b3549457ef1b5f006d524458500960ea2e4d21788a2f0d6d25bd6ebf9e8cd0e3f779523109bfc8f18a8aec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
